export const TODAY_TODO_LIST="TODAY_TODO_LIST";
export const PENDING_LIST="PENDING_LIST";
export const ABANDON_LIST="ABANDON_LIST";
export const COMPLETED_LIST="COMPLETED_LIST";
export const INPROGRESS_LIST="INPROGRESS_LIST";
export const DELETED_LIST="DELETED_LIST";
